nf-graph: better behavior when setting yMin, yMax to null
Previously, setting `yMin` or `yMax` to `undefined` caused

> Error: Invalid value for <g> attribute transform="translate(520, NaN)"

There was no way to set `yMin` or `yMax` to "something if it's defined,
or default behavior otherwise". This now treats the following as
equivalent:

```hbs
{{!-- no yMax specified: --}}
{{nf-graph}}

{{!-- yMax set to undefined: --}}
{{nf-graph yMax=somePropertyThatIsUndefined}}
```